links = {
    "100 REP SQUAT CHALLENGE (Effectively Tone Lift the Booty Thighs) Dude": "https://www.youtube.com/watch?v=J-GQ4iluq8c",
    "100 REP SQUAT CHALLENGE (Effectively Tone Lift the Booty Thighs)": "https://www.youtube.com/watch?v=QifjltKUMCk",
    "50 Squats Challenge [Lean Legs Toned Butt] Effectively Tone Lift the Booty Thighs": "https://www.youtube.com/watch?v=BcoWU6aiBuk",
    "The Most Effective Squat Challenge_ 100 Rep Fitness Blender Squat Challenge": "https://www.youtube.com/watch?v=mGvzVjuY8SY",
    "10 Minute SQUAT CHALLENGE _ at Home Workout": "https://www.youtube.com/watch?v=64Y98mkzAWk",
    "5 Menit Squat Challenge! Bokong dan Paha Pasti Kencang Dengan Workout Ini -  Hip Resistance Band": "https://www.youtube.com/watch?v=VROUNx3dIaA",
    "6 Minute Squat Challenge with Ashley Gaita -  - Home Leg Workout with No Equipment with Ashley Gaita": "https://www.youtube.com/watch?v=BoQtU734GF4",
    "DAY 15 _ 30-day SQUAT challenge _ 100 squats a day _ The Best Booty Challenge": "https://www.youtube.com/watch?v=Lh-jRbKqmcU",
    "6 Minute Squat Workout for the Booty _ 100-Squat Challenge to Grow the Glutes _ Simple Butt Exercise": "https://www.youtube.com/watch?v=tnrvB72vh_M",
    "TABATA Squat Challenge W_ORIGINAL TABATA SONG - 4 Min Squat Variations - Legs on fire - Intervals": "https://www.youtube.com/watch?v=VospL6k3SyI",
    "INTENSE CHEST WORKOUT AT HOME _ 12 MIN PUSH UP WORKOUT _ 30 DAY PUSH UP CHALLENGE": "https://www.youtube.com/watch?v=Jf5_PJCFs-g&ab_channel=TIFFxDAN",
    "200 Push-Up Challenge": "https://www.youtube.com/watch?v=S1JxHrRKNn4&ab_channel=CHRISHERIA",
    "100 Push-Up Workout": "https://www.youtube.com/watch?v=9EFNrqI5Cfo&ab_channel=OnlykindsFitness",
    "10 Min PUSH UP CHALLENGE at Home Workout _ How many can you do": "https://www.youtube.com/watch?v=JEEhNeOZr50&ab_channel=CarolineGirvan",
    "The Perfect PUSH UPS Challenge for Beginners (4 WEEKS Crazy RESULTS)": "https://www.youtube.com/watch?v=3QPDRVRdC9o&ab_channel=NEXTWorkout",
    "Push-Up Workout In 5 Minutes _ In Home": "https://www.youtube.com/watch?v=LWhENdAizkE&ab_channel=OnlykindsFitness",
    "HARDEST 5 MIN PUSH-UP WORKOUT EVER(FOLLOW ALONG)": "https://www.youtube.com/watch?v=7ODJboTuANY&ab_channel=BullyJuice",
    "100 Push Ups in 2 Minutes!! ( CAN YOU DO MORE)": "https://www.youtube.com/watch?v=wCBnl4FK8po&ab_channel=E-LITEFITNESS-FitorQuit",
    "100 Push Ups a Day Challenge (RESULTS in 30 Days)": "https://www.youtube.com/watch?v=f-oSljr2J8w&ab_channel=NEXTWorkout",
    "Push-Up Tutorial_ How To Do a Perfect Push-Up": "https://www.youtube.com/watch?v=ryncZFQCB8I&ab_channel=GMBFitness",
    "10 Minute Squat and Lunge Workout at Home": "https://www.youtube.com/watch?v=p-R0HSfL6nw",
    "1 Minute Workout Lunges Workout": "https://www.youtube.com/watch?v=1-C475PdCmQ",
    "ONE THOUSAND Rep Lunge Challenge _ Leg Workout - No Equipment": "https://www.youtube.com/watch?v=VUO7-6H3SyU",
    "One-Minute Bikini-Booty Challenge_ Split Lunge Jumps": "https://www.youtube.com/watch?v=10Ctr2_B-Fo",
    "Front to back lunges, one minute circuit training exercise": "https://www.youtube.com/watch?v=JHRtLp5Ze9k"
}